name:                toy-lib
version:             0.1.0.0
github:              "toyboot4e/toy-lib"
license:             MIT
author:              "toyboot4e"
maintainer:          "toyboot4e@gmail.com"
copyright:           "2023 toyboot4e"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/toyboot4e/toy-lib>

dependencies:
- array
- base >= 4.7 && < 5
- bytestring
- containers
- extra
- hashable
- heaps
- utility-ht
- primitive
- transformers
- unordered-containers
- vector
- vector-algorithms
- vector-th-unbox

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  toy-lib-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - directory
      - haskell-src-exts
      - process
      - template-haskell
      - temporary

tests:
  toy-lib-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - toy-lib
