name:                toy-lib
version:             0.1.0.0
github:              "toyboot4e/toy-lib"
license:             MIT
author:              "toyboot4e"
maintainer:          "toyboot4e@gmail.com"
copyright:           "2023 toyboot4e"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         For more info, see Github <https://github.com/toyboot4e/toy-lib>

language: GHC2021

# On AtCoder:
# optimization: 2

# See also: <https://docs.google.com/spreadsheets/d/1HXyOXt5bKwhKWXruzUvfMFHQtBxfZQ0047W7VVObnXI/edit#gid=408033513&range=J38>
dependencies:
- array
- base
- bytestring
- containers
- extra
- hashable
- heaps
- utility-ht
- primitive
- transformers
- unordered-containers
- vector
- vector-algorithms

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
# disable:
- -Wno-missing-export-lists

library:
  source-dirs: src

executables:
  toy-lib-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - directory
      - ghc-lib-parser
      - ghc-lib-parser-ex
      - process
      - template-haskell
      - temporary
      - toy-lib

tests:
  toy-lib-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - toy-lib
    - doctest
