#!/usr/bin/env -S bash +x

rm -rf gh-pages/*
cp -r ./dist-newstyle/build/x86_64-linux/ghc-9.4.6/toy-lib-0.1.0.0/doc/html/toy-lib/* gh-pages
cd gh-pages && git add . && git commit -m 'update' && git push

