#!/usr/bin/env bash

# Be sure to set `DROPBOX_TOKEN` before run.
# Run from the repository root.

file="$(basename "$(ls verify/src/*.hs | fzf)")"

cd verify

# assuming `verifycation-helper` package is installed via `venv`
# (see `:/verify/README.org`)
source .venv/bin/activate

oj-verify run "src/$file" # -j 8

