#!/usr/bin/env bash

# Be sure to set `DROPBOX_TOKEN` before run.
# Run from the repository root:
cd verify

# assuming `verifycation-helper` package is installed via `venv`
# (see `:/verify/README.org`)
source .venv/bin/activate

touch src/*.hs
oj-verify run src/*.hs # -j 8

