#!/usr/bin/env bash

# Be sure to set `DROPBOX_TOKEN` before run.
# Run from the repository root.

# TIP: c-p for previous historb
file="$(basename "$(ls verify/src/*.hs | fzf --history ~/.fzf-history)")"
cd verify

touch "src/$file"
./.venv/bin/oj-verify run "src/$file" # -j 8

