#!/usr/bin/env bash

# Be sure to set `DROPBOX_TOKEN` before run.
# Run from the repository root.

# TIP: c-p for previous historb
file="$(basename "$(ls verify/src/*.hs | fzf --history ~/.fzf-history)")"
cd verify

# assuming `verifycation-helper` package is installed via `venv`
# (see `:/verify/README.org`)
# $ python -m venv .venv
# (.venv) $ # source .venv/bin/activate # activate (on bash)
# (.venv) $ pip3 install online-judge-verify-helper

./.venv/bin/oj-verify run "src/$file" # -j 8

